#!/usr/bin/env python3
import sys
from pathlib import Path

def create_cpp_variable_name(module_name: str) -> str:
    sanitized = module_name.replace('/', '_').replace('.', '_')
    return f"Std_{sanitized}_Source"

def main():
    if len(sys.argv) != 3:
        print(f"Error: Invalid number of arguments.", file=sys.stderr)
        print(f"Usage: {sys.argv[0]} <input_directory> <output_header_path>", file=sys.stderr)
        sys.exit(1)

    source_dir = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    if not source_dir.is_dir():
        print(f"Error: Input directory '{source_dir}' does not exist.", file=sys.stderr)
        sys.exit(1)

    print(f"Searching for .aleng files in: {source_dir}")

    libraries = []
    for aleng_file in sorted(source_dir.rglob('*.aleng')):
        try:
            module_name = aleng_file.relative_to(source_dir).with_suffix('').as_posix()

            cpp_var = create_cpp_variable_name(module_name)
            content = aleng_file.read_text(encoding='utf-8')

            libraries.append({
                'source_path': aleng_file.relative_to(source_dir.parent),
                'module_name': module_name,
                'cpp_var': cpp_var,
                'content': content
            })
        except Exception as e:
            print(f"Error processing file {aleng_file}: {e}", file=sys.stderr)
            sys.exit(1)

    if not libraries:
        print("Warning: No .aleng files found in the standard library directory.")

    header_content = [
        "// THIS FILE IS AUTOMATICALLY GENERATED BY scripts/generate_stdlib.py",
        "// DO NOT EDIT MANUALLY\n",
        "#pragma once",
        "#include <string>",
        "#include <unordered_map>\n",
        "namespace Aleng::StdLib",
        "{",
    ]

    # 1. Define all source strings as C++ raw string literals
    for lib in libraries:
        header_content.append(f"    // Source from {lib['source_path'].as_posix()}")
        header_content.append(f'    const char* {lib["cpp_var"]} = R"ALENG_STDLIB({lib["content"]})ALENG_STDLIB";\n')

    header_content.extend([
        "    // Function to register all standard libraries",
        "    inline std::unordered_map<std::string, std::string> GetLibraries()",
        "    {",
        "        std::unordered_map<std::string, std::string> libs;",
    ])

    if not libraries:
        header_content.append("        // No standard libraries were found to register.")
    else:
        for lib in libraries:
            header_content.append(f'        libs["std/{lib["module_name"]}"] = {lib["cpp_var"]};')

    header_content.extend([
        "        return libs;",
        "    }",
        "}"
    ])

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text('\n'.join(header_content) + '\n', encoding='utf-8')
        print(f"Successfully generated standard library header: {output_path}")
    except Exception as e:
        print(f"Error writing to output file {output_path}: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()